/**
 * DealDNA — Phase 4
 * lib/precedents.ts
 *
 * Centralized institutional precedent database.
 * Single source of truth — imported everywhere (scoring, citations, network, report).
 * Cast to ScoredPrecedent[] after rankPrecedents() populates dynamic scores.
 */

import type { ScoredPrecedent } from "./scoringEngine";

// ─── Base Precedent (pre-scoring) ─────────────────────────────────────────────

export type BasePrecedent = Omit<
  ScoredPrecedent,
  "similarityScore" | "confidenceScore" | "dimensionScores"
>;

export const PRECEDENTS: BasePrecedent[] = [
  // ── Industrials / North America ──────────────────────────────────────────
  {
    id: "p001",
    company: "Apex Manufacturing Partners",
    sponsor: "KKR",
    year: 2019,
    sector: "Industrials",
    geography: "North America",
    outcome: "Strong Exit",
    entryEV: 850,
    leverage: 6.0,
    evEbitda: 11.2,
    revenue: 210,
    ebitdaMargin: 26,
    moic: 3.2,
    irr: 28,
    holdPeriod: 4,
    riskClusters: ["leverage", "cyclicality", "customer concentration"],
    keyLessons: [
      "Operational efficiency drove 400bps margin improvement over hold",
      "Exit timing aligned with credit cycle peak — crucial for return",
      "Management incentive realignment in year 1 accelerated EBITDA growth",
    ],
    hiddenRisks: [
      "Management dependency on founder CEO created key-person fragility",
      "Channel concentration in top 3 accounts amplified churn risk",
      "Deferred capex overhang understated in diligence model",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "enterprise",
  },
  {
    id: "p002",
    company: "Frontier Services Group",
    sponsor: "Carlyle",
    year: 2021,
    sector: "Business Services",
    geography: "North America",
    outcome: "Partial Exit",
    entryEV: 620,
    leverage: 5.5,
    evEbitda: 10.8,
    revenue: 180,
    ebitdaMargin: 24,
    moic: 2.1,
    irr: 19,
    holdPeriod: 3,
    riskClusters: ["integration risk", "pricing pressure", "technology displacement"],
    keyLessons: [
      "Bolt-on strategy underdelivered synergies by 35% vs. model",
      "Enterprise customer stickiness was materially higher than modeled",
      "SaaS migration cost significantly exceeded initial diligence estimates",
    ],
    hiddenRisks: [
      "SaaS competitor disruption underestimated in addressable market sizing",
      "Working capital seasonality not properly modeled in bridge",
      "Integration management bandwidth stretched across 4 concurrent add-ons",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "enterprise",
  },
  {
    id: "p003",
    company: "Nordic Logistics Partners",
    sponsor: "EQT",
    year: 2022,
    sector: "Industrials",
    geography: "Western Europe",
    outcome: "Hold",
    entryEV: 1100,
    leverage: 7.2,
    evEbitda: 13.5,
    revenue: 320,
    ebitdaMargin: 22,
    moic: undefined,
    irr: undefined,
    holdPeriod: 2,
    riskClusters: ["rate sensitivity", "leverage", "demand cyclicality"],
    keyLessons: [
      "Rate environment compressed equity returns by 150bps vs. model",
      "Geographic diversification proved a structural positive in demand shock",
      "High leverage entering rate-rising regime destroyed refinancing flexibility",
    ],
    hiddenRisks: [
      "Covenant breach at 6.5x threshold with limited headroom buffer",
      "FX exposure on non-Euro revenue streams left unhedged",
      "Subcontractor dependency in last-mile operations underestimated",
    ],
    macroRegime: "rate-rising",
    revenueModel: "transactional",
    customerSegment: "enterprise",
  },
  {
    id: "p004",
    company: "Meridian Infrastructure Holdings",
    sponsor: "Blackstone",
    year: 2018,
    sector: "Industrials",
    geography: "North America",
    outcome: "Strong Exit",
    entryEV: 1400,
    leverage: 5.0,
    evEbitda: 12.0,
    revenue: 440,
    ebitdaMargin: 31,
    moic: 3.8,
    irr: 32,
    holdPeriod: 5,
    riskClusters: ["regulatory", "capex", "customer concentration"],
    keyLessons: [
      "Long-duration contracts de-risked revenue profile through rate cycle",
      "Management incentive alignment was critical to above-model performance",
      "Infrastructure-adjacent positioning supported premium exit valuation",
    ],
    hiddenRisks: [
      "Regulatory reclassification risk underweighted in base-case model",
      "Deferred capex overhang of $40M not disclosed in initial diligence",
      "Single-sector concentration created correlated downside risk",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "government",
  },
  {
    id: "p005",
    company: "Vantage Industrial Systems",
    sponsor: "Advent International",
    year: 2023,
    sector: "Industrials",
    geography: "North America",
    outcome: "Hold",
    entryEV: 720,
    leverage: 6.5,
    evEbitda: 10.5,
    revenue: 195,
    ebitdaMargin: 27,
    moic: undefined,
    irr: undefined,
    holdPeriod: 1,
    riskClusters: ["leverage", "cyclicality", "technology displacement"],
    keyLessons: [
      "Rate environment materially impacted exit optionality vs. vintage plan",
      "Operational improvement outperformed model by 20% — quality of management",
      "Near-term covenant pressure requires Q3 waiver negotiation",
    ],
    hiddenRisks: [
      "Near-term refinancing exposure at maturity wall",
      "Supply chain concentration in 2 offshore component suppliers",
      "Automation capex requirements not modeled in 5-year plan",
    ],
    macroRegime: "rate-rising",
    revenueModel: "recurring",
    customerSegment: "enterprise",
  },
  // ── Technology / SaaS ─────────────────────────────────────────────────────
  {
    id: "p006",
    company: "Prismatic Software Holdings",
    sponsor: "Vista Equity Partners",
    year: 2020,
    sector: "Technology",
    geography: "North America",
    outcome: "Strong Exit",
    entryEV: 980,
    leverage: 5.2,
    evEbitda: 18.5,
    revenue: 160,
    ebitdaMargin: 32,
    moic: 4.1,
    irr: 35,
    holdPeriod: 3,
    riskClusters: ["customer churn", "competitive moat", "integration complexity"],
    keyLessons: [
      "Vista playbook of sales force optimization added 8% ARR growth",
      "Enterprise contract extension from 1yr to 3yr significantly de-risked profile",
      "Add-on M&A expanded TAM and supported premium exit multiple",
    ],
    hiddenRisks: [
      "NRR compression in SMB cohort masked by enterprise growth headline",
      "Technical debt in legacy codebase required $12M remediation spend",
      "Key engineering talent attrition risk post-close materialized",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "enterprise",
  },
  {
    id: "p007",
    company: "Nexora Data Intelligence",
    sponsor: "Thoma Bravo",
    year: 2022,
    sector: "Technology",
    geography: "North America",
    outcome: "Hold",
    entryEV: 1650,
    leverage: 6.8,
    evEbitda: 22.0,
    revenue: 280,
    ebitdaMargin: 34,
    moic: undefined,
    irr: undefined,
    holdPeriod: 2,
    riskClusters: ["rate sensitivity on premium multiple", "AI displacement", "customer concentration"],
    keyLessons: [
      "Entry at 22x EV/EBITDA created significant multiple compression risk",
      "Thoma Bravo operational playbook delivered 600bps margin improvement",
      "AI feature race accelerating faster than product roadmap can adapt",
    ],
    hiddenRisks: [
      "Top 3 customers representing 45% of ARR with renewal cliff in year 3",
      "OpenAI/Microsoft competitive displacement materially underestimated",
      "Sales cycle elongation in enterprise softening NTM pipeline visibility",
    ],
    macroRegime: "rate-rising",
    revenueModel: "recurring",
    customerSegment: "enterprise",
  },
  // ── Healthcare / Life Sciences ────────────────────────────────────────────
  {
    id: "p008",
    company: "Catalyst Health Services",
    sponsor: "Warburg Pincus",
    year: 2020,
    sector: "Healthcare",
    geography: "North America",
    outcome: "Strong Exit",
    entryEV: 560,
    leverage: 4.5,
    evEbitda: 14.0,
    revenue: 130,
    ebitdaMargin: 29,
    moic: 3.5,
    irr: 31,
    holdPeriod: 4,
    riskClusters: ["regulatory change", "reimbursement risk", "labor cost inflation"],
    keyLessons: [
      "Regulatory tailwinds from ACA expansion materially exceeded model",
      "Labor arbitrage through geographic diversification protected margins",
      "Platform consolidation thesis validated — 6 bolt-ons at 8-10x EV/EBITDA",
    ],
    hiddenRisks: [
      "CMS reimbursement rate change risk underweighted in base case",
      "Labor market tightness created wage inflation of 8% vs. 3% modeled",
      "State-level regulatory variance added complexity to multi-market ops",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "government",
  },
  // ── Business Services ─────────────────────────────────────────────────────
  {
    id: "p009",
    company: "Hallmark Outsourcing Group",
    sponsor: "Bain Capital",
    year: 2019,
    sector: "Business Services",
    geography: "North America",
    outcome: "Partial Exit",
    entryEV: 430,
    leverage: 5.8,
    evEbitda: 9.8,
    revenue: 145,
    ebitdaMargin: 21,
    moic: 2.3,
    irr: 22,
    holdPeriod: 3,
    riskClusters: ["pricing pressure", "labor automation", "contract renewal concentration"],
    keyLessons: [
      "Offshore delivery model required 18 months to stabilize — model underestimated",
      "Top 3 contracts representing 60% revenue renewed — but with pricing concessions",
      "Technology automation investment created SG&A efficiency not in base case",
    ],
    hiddenRisks: [
      "Contract pricing renegotiation cycle compresses margin in year 2-3",
      "Offshore delivery risk from geopolitical events not modeled",
      "Key account manager attrition to competitors took 6 months to stabilize",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "enterprise",
  },
  {
    id: "p010",
    company: "Pinnacle Facilities Management",
    sponsor: "Apollo Global",
    year: 2023,
    sector: "Business Services",
    geography: "North America",
    outcome: "Hold",
    entryEV: 580,
    leverage: 6.2,
    evEbitda: 10.2,
    revenue: 175,
    ebitdaMargin: 25,
    moic: undefined,
    irr: undefined,
    holdPeriod: 1,
    riskClusters: ["rate sensitivity", "input cost inflation", "contract concentration"],
    keyLessons: [
      "Facilities management is relatively rate-insensitive on revenue — but debt cost matters",
      "Input cost pass-through clauses in long-term contracts proved valuable",
      "Public sector exposure provided revenue stability but limits margin upside",
    ],
    hiddenRisks: [
      "Energy price pass-through lag creates quarterly P&L volatility",
      "Union contract renegotiation in year 2 adds 150-200bps labor cost",
      "CRE occupancy trends reducing addressable market in office segment",
    ],
    macroRegime: "rate-rising",
    revenueModel: "recurring",
    customerSegment: "government",
  },
  // ── Consumer / Retail ─────────────────────────────────────────────────────
  {
    id: "p011",
    company: "Archer Consumer Brands",
    sponsor: "Leonard Green",
    year: 2018,
    sector: "Consumer",
    geography: "North America",
    outcome: "Strong Exit",
    entryEV: 720,
    leverage: 5.5,
    evEbitda: 11.5,
    revenue: 350,
    ebitdaMargin: 18,
    moic: 3.0,
    irr: 26,
    holdPeriod: 4,
    riskClusters: ["channel disruption", "brand equity erosion", "private label competition"],
    keyLessons: [
      "DTC channel pivot added 600bps margin improvement — critical to exit valuation",
      "Brand portfolio rationalization released $45M working capital",
      "Retailer concentration risk mitigated through accelerated channel diversification",
    ],
    hiddenRisks: [
      "Amazon private label competition materially accelerated post-close",
      "Influencer marketing ROI decay faster than management assumed",
      "Commodity input cost (packaging, ingredients) unhedged exposure",
    ],
    macroRegime: "rate-stable",
    revenueModel: "transactional",
    customerSegment: "consumer",
  },
  // ── Energy / Infrastructure ───────────────────────────────────────────────
  {
    id: "p012",
    company: "Resonance Energy Infrastructure",
    sponsor: "Brookfield Asset Management",
    year: 2021,
    sector: "Energy",
    geography: "North America",
    outcome: "Hold",
    entryEV: 2100,
    leverage: 6.0,
    evEbitda: 13.0,
    revenue: 510,
    ebitdaMargin: 38,
    moic: undefined,
    irr: undefined,
    holdPeriod: 3,
    riskClusters: ["regulatory", "energy transition risk", "counterparty risk"],
    keyLessons: [
      "Long-term contracted revenue (15yr+) provides exceptional downside protection",
      "ESG tailwinds supporting premium valuation vs. conventional energy comps",
      "Infrastructure leverage capacity higher than typical PE — 6x comfortable",
    ],
    hiddenRisks: [
      "Regulatory reclassification could compress permissible leverage",
      "Counterparty credit risk on offtake agreements not stress-tested",
      "Energy transition technology disruption risk to core asset class",
    ],
    macroRegime: "rate-rising",
    revenueModel: "recurring",
    customerSegment: "government",
  },
  // ── Financial Services ────────────────────────────────────────────────────
  {
    id: "p013",
    company: "Stratum Financial Solutions",
    sponsor: "General Atlantic",
    year: 2022,
    sector: "Financial Services",
    geography: "North America",
    outcome: "Hold",
    entryEV: 890,
    leverage: 4.8,
    evEbitda: 16.5,
    revenue: 195,
    ebitdaMargin: 33,
    moic: undefined,
    irr: undefined,
    holdPeriod: 2,
    riskClusters: ["regulatory risk", "credit cycle exposure", "technology disruption"],
    keyLessons: [
      "Capital-light model supports higher leverage than balance sheet lenders",
      "Regulatory uncertainty requires dedicated compliance infrastructure investment",
      "Cross-sell motion across product suite outperformed expectations by 40%",
    ],
    hiddenRisks: [
      "CFPB regulatory changes could restrict core product economics",
      "Credit cycle deterioration compresses origination volume faster than model",
      "Open banking API disruption to distribution moat underestimated",
    ],
    macroRegime: "rate-rising",
    revenueModel: "recurring",
    customerSegment: "smb",
  },
  // ── Western Europe ────────────────────────────────────────────────────────
  {
    id: "p014",
    company: "Albrecht Industrial Group",
    sponsor: "CVC Capital Partners",
    year: 2020,
    sector: "Industrials",
    geography: "Western Europe",
    outcome: "Strong Exit",
    entryEV: 760,
    leverage: 5.3,
    evEbitda: 10.8,
    revenue: 230,
    ebitdaMargin: 24,
    moic: 2.8,
    irr: 24,
    holdPeriod: 4,
    riskClusters: ["FX exposure", "labor regulation", "demand cyclicality"],
    keyLessons: [
      "Pan-European platform strategy supported exit at premium to standalone valuation",
      "Currency hedging program protected USD-equivalent returns for LP base",
      "German labor regulation added friction to restructuring but protected relationships",
    ],
    hiddenRisks: [
      "Euro-denominated revenue creates FX volatility for USD-reporting fund",
      "European labor law creates restructuring cost asymmetry vs. US comps",
      "Geopolitical risk premium on Eastern European supply chain exposure",
    ],
    macroRegime: "rate-stable",
    revenueModel: "transactional",
    customerSegment: "enterprise",
  },
  // ── Asia-Pacific ──────────────────────────────────────────────────────────
  {
    id: "p015",
    company: "Cascade Technology Ventures",
    sponsor: "TPG Capital",
    year: 2021,
    sector: "Technology",
    geography: "Asia Pacific",
    outcome: "Partial Exit",
    entryEV: 1250,
    leverage: 4.2,
    evEbitda: 19.5,
    revenue: 185,
    ebitdaMargin: 31,
    moic: 1.8,
    irr: 15,
    holdPeriod: 3,
    riskClusters: ["regulatory risk", "geopolitical risk", "currency risk"],
    keyLessons: [
      "APAC regulatory environment significantly more complex than diligence indicated",
      "Geopolitical tensions created unexpected friction in cross-border data flows",
      "Local management partnership structure critical to navigating regulatory environment",
    ],
    hiddenRisks: [
      "China tech regulatory crackdown affected comparable valuations severely",
      "Cross-border data restriction laws not fully modeled in operating structure",
      "Currency volatility eroded USD returns despite strong local performance",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "enterprise",
  },
  // ── Mid-Market Industrials ────────────────────────────────────────────────
  {
    id: "p016",
    company: "Corsair Precision Components",
    sponsor: "Platinum Equity",
    year: 2022,
    sector: "Industrials",
    geography: "North America",
    outcome: "Hold",
    entryEV: 380,
    leverage: 7.0,
    evEbitda: 9.5,
    revenue: 120,
    ebitdaMargin: 22,
    moic: undefined,
    irr: undefined,
    holdPeriod: 2,
    riskClusters: ["supply chain risk", "leverage", "customer concentration"],
    keyLessons: [
      "Platinum operational improvement playbook delivered 250bps margin improvement",
      "Supply chain resilience investment of $8M required but unplanned",
      "Single large OEM customer (67% revenue) creates binary outcome risk",
    ],
    hiddenRisks: [
      "OEM customer insourcing threat understated in competitive analysis",
      "7.0x leverage leaves minimal headroom at current EBITDA run-rate",
      "Tariff exposure on raw material imports not modeled in base case",
    ],
    macroRegime: "rate-rising",
    revenueModel: "transactional",
    customerSegment: "enterprise",
  },
  // ── Healthcare Services ───────────────────────────────────────────────────
  {
    id: "p017",
    company: "Meridian Physician Partners",
    sponsor: "Welsh Carson",
    year: 2019,
    sector: "Healthcare",
    geography: "North America",
    outcome: "Strong Exit",
    entryEV: 640,
    leverage: 5.0,
    evEbitda: 13.5,
    revenue: 175,
    ebitdaMargin: 27,
    moic: 3.6,
    irr: 30,
    holdPeriod: 4,
    riskClusters: ["regulatory", "physician recruitment", "reimbursement risk"],
    keyLessons: [
      "Value-based care contracts proved significantly more defensible than fee-for-service",
      "Physician equity partnership structure critical for recruitment and retention",
      "Platform scale enabled payer contract renegotiation — 200bps margin uplift",
    ],
    hiddenRisks: [
      "CMS regulatory changes on physician-owned hospital structures",
      "Physician group culture integration risk underestimated vs. corporate services",
      "Telehealth competitive disruption to core in-person visit model",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "consumer",
  },
  // ── Software / Mid-Market ─────────────────────────────────────────────────
  {
    id: "p018",
    company: "Archon Software Holdings",
    sponsor: "Francisco Partners",
    year: 2021,
    sector: "Technology",
    geography: "North America",
    outcome: "Partial Exit",
    entryEV: 460,
    leverage: 5.8,
    evEbitda: 14.0,
    revenue: 95,
    ebitdaMargin: 33,
    moic: 2.4,
    irr: 21,
    holdPeriod: 3,
    riskClusters: ["churn risk", "product roadmap execution", "competitive intensity"],
    keyLessons: [
      "Go-to-market transformation from direct to channel added scale without cost",
      "Net revenue retention improvement from 98% to 115% drove multiple expansion",
      "Product consolidation from 4 to 1 platform reduced R&D burn by 40%",
    ],
    hiddenRisks: [
      "Enterprise deal cycle elongation reduced NTM bookings predictability",
      "Cloud migration requirement created 12-month revenue recognition gap",
      "Salesforce integration dependency concentrated partnership risk",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "smb",
  },
  // ── Special Situations ────────────────────────────────────────────────────
  {
    id: "p019",
    company: "Northstar Carve-Out Holdings",
    sponsor: "Advent International",
    year: 2020,
    sector: "Industrials",
    geography: "North America",
    outcome: "Strong Exit",
    entryEV: 930,
    leverage: 5.5,
    evEbitda: 11.8,
    revenue: 270,
    ebitdaMargin: 29,
    moic: 3.4,
    irr: 29,
    holdPeriod: 4,
    riskClusters: ["carve-out complexity", "TSA dependency", "standalone cost structure"],
    keyLessons: [
      "Carve-out complexity required 24 months to fully stand up — 2x model estimate",
      "TSA exit ahead of schedule created $6M annualized savings vs. model",
      "Standalone branding investment proved ROI-positive in customer retention",
    ],
    hiddenRisks: [
      "Corporate parent IP dependencies not fully identified in carve-out scope",
      "Standalone IT infrastructure cost significantly underestimated in model",
      "Parent customer relationships did not transfer at modeled retention rates",
    ],
    macroRegime: "rate-stable",
    revenueModel: "recurring",
    customerSegment: "enterprise",
  },
  {
    id: "p020",
    company: "Summit Growth Equity Partners",
    sponsor: "TA Associates",
    year: 2023,
    sector: "Business Services",
    geography: "North America",
    outcome: "Hold",
    entryEV: 340,
    leverage: 3.5,
    evEbitda: 12.5,
    revenue: 85,
    ebitdaMargin: 32,
    moic: undefined,
    irr: undefined,
    holdPeriod: 1,
    riskClusters: ["growth deceleration", "founder dependency", "talent retention"],
    keyLessons: [
      "Growth equity structure requires different management engagement vs. buyout",
      "Founder retention economics critical — departing founders create customer risk",
      "ARR growth rate deceleration from 40% to 18% compressed entry multiple justification",
    ],
    hiddenRisks: [
      "Growth deceleration narrative may require re-underwriting of exit multiple",
      "Founder CEO succession planning not adequately structured at close",
      "Sales team turnover during transition created 2-quarter pipeline disruption",
    ],
    macroRegime: "rate-rising",
    revenueModel: "recurring",
    customerSegment: "smb",
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Get precedents as ScoredPrecedent[] with zero scores (for type compatibility) */
export function getPrecedentsForScoring(): import("./scoringEngine").ScoredPrecedent[] {
  return PRECEDENTS.map((p) => ({
    ...p,
    similarityScore: 0,
    confidenceScore: 0,
    dimensionScores: {
      sector: 0,
      leverage: 0,
      margin: 0,
      geography: 0,
      customerModel: 0,
      revenueModel: 0,
      macroRegime: 0,
    },
  }));
}

/** Get precedent by ID */
export function getPrecedentById(id: string): BasePrecedent | undefined {
  return PRECEDENTS.find((p) => p.id === id);
}

/** Get precedents by sector */
export function getPrecedentsBySector(sector: string): BasePrecedent[] {
  return PRECEDENTS.filter(
    (p) => p.sector.toLowerCase().includes(sector.toLowerCase())
  );
}

/** Get strong exits only */
export function getStrongExits(): BasePrecedent[] {
  return PRECEDENTS.filter((p) => p.outcome === "Strong Exit");
}

export default PRECEDENTS;
